### ISSUE TITLE
Cannot call method 'splice' of undefined

### ISSUE THREAD

**Issue by VinSpee** [postcss/postcss-custom-properties#17]
Just upgraded to postcss 4.0 and gulp-postcss 4.0 and now this is happening:

```
{ [TypeError: Cannot call method 'splice' of undefined]
  name: 'TypeError',
  message: 'Cannot call method \'splice\' of undefined',
  stack: 'TypeError: Cannot call method \'splice\' of undefined\n    at /Users/vinspee/Projects/TeamMate/prototype/node_modules/postcss-custom-properties/index.js:67:23\n    at /Users/vinspee/Projects/TeamMate/prototype/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:192:20\n    at /Users/vinspee/Projects/TeamMate/prototype/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:127:18\n    at Root.Container.each (/Users/vinspee/Projects/TeamMate/prototype/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:105:14)\n    at Root.Container.eachInside (/Users/vinspee/Projects/TeamMate/prototype/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:126:15)\n    at Root.Container.eachRule (/Users/vinspee/Projects/TeamMate/prototype/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:190:15)\n    at Array.2 (/Users/vinspee/Projects/TeamMate/prototype/node_modules/postcss-custom-properties/index.js:29:11)\n    at PostCSS.process (/Users/vinspee/Projects/TeamMate/prototype/node_modules/gulp-postcss/node_modules/postcss/lib/postcss.js:47:35)\n    at DestroyableTransform.transform [as _transform] (/Users/vinspee/Projects/TeamMate/prototype/node_modules/gulp-postcss/index.js:45:26)\n    at DestroyableTransform.Transform._read (/Users/vinspee/Projects/TeamMate/prototype/node_modules/gulp-postcss/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-postcss' }
```

**Comment by MoOx** [comment]
Most postcss plugins haven't been updated for postcss 4.
About time.
